data:
  pairs:
    [
      "EURUSDm",
      "GBPUSDm",
      "USDJPYm",
      "AUDUSDm",
      "NZDUSDm",
      "USDCADm",
      "USDCHFm",
      "EURJPYm",
      "GBPJPYm",
      "AUDJPYm",
      "NZDJPYm",
      "CADJPYm",
      "CHFJPYm",
      "EURGBPm",
      "EURAUDm",
      "USDZARm",
      "XAUUSDm",
    ]
  timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"]
